### ISSUE TITLE
Issue with PHP7.0 and patch SUPEE-9767

### ISSUE THREAD

**Issue by mrobichaudb** [Inchoo/Inchoo_PHP7#117]
The new patch change 2 function in Enterprise_PageCache_Model_Observer and now use Zend_Json::decode. These throw error if an empty string is sent in php7. 

It need to be rewritten to use the core helper jsonDecode function that is already rewritten in the PHP7 module. 

Enterprise_PageCache_Model_Observer (
line 177: `$exceptions = @Zend_Json::decode($exceptions);`
and Line 244 :    `$cachedSslOffloaderHeader = trim(@Zend_Json::decode($cachedSslOffloaderHeader));`

**Comment by icurdinj** [comment]
Nice catch. Until I get around to doing it, pull requests are welcome.

**Comment by digitalpianism** [comment]
More info can be found here btw: https://magento.stackexchange.com/a/177036/2380

**Comment by ivanweiler** [comment]
Just a late update regarding this.

After release of SUPEE-9767, Magento released SUPEE-9767-V2 and asked users to revert the first patch. Issue doesn't exists in V2 since they reverted code to initial serialize/unserialize;

Issue also doesn't exists in latest EE (1.14.3.6, 1.14.3.7), so I believe we can close this.

When I find some time, I'll create Wiki page here and collect all similar notes and issues to help everyone.
