### ISSUE TITLE
Enterprise 1.14.2.2 compatibility?

### ISSUE THREAD

**Issue by craigcarnell** [Inchoo/Inchoo_PHP7#14]

**Comment by icurdinj** [comment]
Not tested yet. I guess what we have now is a good starting point, though, since core should be basically the same.
If it turns out there are EE specific fixes needed, we'll put them into a separate branch and make a separate release.
Testing is welcome. Pull requests are welcome. (This is becoming somewhat of a mantra on this project.) :-)

**Comment by craigcarnell** [comment]
Seems to work fine
