### ISSUE TITLE
Better fix Varien File Uploader in local folder the over Mage

### ISSUE THREAD

**Issue by AJakob1983** [Inchoo/Inchoo_PHP7#19]
This extensions fix the Uploader.php File in the Local Mage Folder. But the better way is to create a Varien File Folder inside local an fix the bug inside this folder.

$params['object']->{$params['method']}($this->_file['tmp_name']);

Some Extension will use the Varien File and not the Mage file.

**Comment by icurdinj** [comment]
The principle we took when writing this extension is to fix things on the topmost level of inheritance, and avoid rewriting the core whenever possible.
Extension incompatibilites should be fixed in the extensions themselves.
But, hey, this extension is free, so fork your own version, and do things in any way you like!
