### ISSUE TITLE
Magento connect manager error install

### ISSUE THREAD

**Issue by Insect2015** [Inchoo/Inchoo_PHP7#33]
Hello support,

When I update or install a exstension I get the follow error.

CONNECT ERROR: Package community/symmetrics_trustedrating 0.2.6: requires PHP version >= 5.2.0 and <= 6.0.0 current is: 7.0.4-1byte1

Best regards,
Michel

**Comment by durzel** [comment]
This isn't an issue with this module.

Using Magento Connect after you've upgraded to PHP 7.0 is very risky since many extensions will have these kinds of min/max PHP version restrictions in their package XML.

If in doubt you should attempt to upgrade on a dev site first.  Alternatively you can edit the package.xml and repackage & reinstall the archive.

**Comment by peterjaap** [comment]
Please close.

**Comment by icurdinj** [comment]
I think this is the right place to file that issue: https://github.com/symmetrics/trustedshops_trustedrating/issues
