### ISSUE TITLE
Checkout redirects back to cart magento 1.9.3.1

### ISSUE THREAD

**Issue by Feggel** [Inchoo/Inchoo_PHP7#91]
With magento 1.9.3.1 and PHP7 enabled, the checkout redirects back to the cart.
Everything works fine up untill the payment page, so after the shipping method you click on next -> boom, you're back in the cart.

I reverted back to PHP5.6 and the issue was gone. Back to PHP7 and the issue was present.
I'm not sure how to provide an error report, but if someone could tell me how, I'm happy to provide one.

**Comment by durzel** [comment]
First of all - you need to make sure you are using the correct version of Inchoo_PHP7.  Did you upgrade it from 1.x to the 2.0.0 version required for Magento 1.9.3.x ?

Alternatively it could be a session permissions problem.  I had some session issues when I upgraded (copied the 1.9.3.1 files on top) from 1.9.2.4 + SUPEE-8788-V2 install with the 1.9.3.1 files yesterday.  I am on PHP 7.0.12 too.

I initially saw some strange behaviour with adding products to cart - it would just redirect to an empty cart page when adding.  The `var/log/system.log` was saying the following:

`2016-11-16T11:27:42+00:00 ERR (3): Warning: session_start(): Session data file is not created by your uid  in /home/magento-dev/public_html/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 134`

See if you have anything similar.  It might be worth wiping your existing session data too, this fixed the problem for me.

I don't think this is a problem with this extension because I'm able to place orders etc fine now.

**Comment by Feggel** [comment]
Allright thanks. I'll try it out. Report back afterwards.

I did have a clean install of 1.9.3.0 and upgraded to 1.9.3.1.
Then I installed Inchoo_PHP7 version 2.0.0.

**Comment by Feggel** [comment]
I whiped my session data.

Made 100% sure that I use version 2.0.0.
Problem still persists.

The only error I get in var/log/system.php is:
`2016-11-17T09:22:09+00:00 ERR (3): Notice: Undefined index: test  in /home/public_html/app/code/local/MJ/Customsmtp/Model/Observer.php on line 32`

I'm not sure what it means though...

There are no other errors in the log file.
What else could I do?

**Comment by durzel** [comment]
To confirm - where are you ending up on an empty cart?  Is it at the final step of the checkout?  Are you otherwise able to add and remove items from the cart, log in with a registered account, etc?

Are you using the standard Magento one page checkout?

**Comment by Feggel** [comment]
Standard magento checkout. Redirected back to cart with product still in it.

I only had one extension installed prior, but I just remembered to that I removed it correctly.
I just confirmed that it was an extension which wasn't disabled / removed correctly.
It was the extension: TIG MY PARCEL POSTNL.
After disabling it and removing it correctly also from database, checkout is working fine now!

Sorry to have bothered you. Thank you for your guidance and help!
