### ISSUE TITLE
How to install a new magento 1.9.3 on a fresh php7 with this 

### ISSUE THREAD

**Issue by cedriclombardot** [Inchoo/Inchoo_PHP7#92]
I've tried with downloader but got errors like 

Package community/Interface_Frontend_Rwd_Default 1.9.3.1: requires PHP version >= 5.2.0 and <= 6.0.0 current is: 7.0.8-0ubuntu0.16.04.3

Thanks in advance

**Comment by ivanweiler** [comment]
Manually, without downloader, goes something like this:

- download whole Magento 1.9.3 from Magento download Archive, unpack to proper server folder
- download this extension, unpack, copy/paste to Magento root folder (merge with Magento)
- run Magento through browser, installer should open and work

With downloader, since it's fetching packages from Magento, I think the only way would be to patch downloader itself, to remove version check, but this isn't covered with this module.

Hope it helps ..

**Comment by cedriclombardot** [comment]
Thx
