### ISSUE TITLE
7.1 support?

### ISSUE THREAD

**Issue by craigcarnell** [Inchoo/Inchoo_PHP7#94]

**Comment by icurdinj** [comment]
Not tested yet, but due to very little gain from 7.1 compared to 7.0, it isn't a priority.

**Comment by craigcarnell** [comment]
@icurdinj The only benchmarks I've found so far:

http://phoronix.com/scan.php?page=news_item&px=PTS-PHP-7.1-Benchmarks

**Comment by jgeerdink** [comment]
sd

**Comment by jgeerdink** [comment]
Just tried it today with 7.1, but that does not work properly. After upgrading, it is not possible to open any type of order in the Magento backend.

**Comment by ivanweiler** [comment]
Just tested Magento 1.9.3.1 on PHP 7.1.0, everything seems fine here. 

Only one log warrning mentioned in separate issue https://github.com/Inchoo/Inchoo_PHP7/issues/97 , but everything is working.

@jgeerdink Orders are working fine here, both My Account and admin. Did you find out what's wrong, maybe is related to payment method used, which payment is used on that orders?

**Comment by jgeerdink** [comment]
Strange, when I change to php 7.1 I see the following when opening a order. It does not load the order in total. How can I solve that?

![Screenshot](https://cloud.githubusercontent.com/assets/10529399/22326606/af83fe6c-e3b3-11e6-9398-4b0a1a9af49e.png)

**Comment by icurdinj** [comment]
Supported, but pointless: https://github.com/Inchoo/Inchoo_PHP7/wiki/RunningOnPHP7.1

**Comment by gamort** [comment]
I'm not so sure about pointless.   If the issue is mainly deprecation warnings, I think a better solution would be to disable those warnings[since no one reads them anyway]

The benefit's are mainly regarding perceived PCI Compliance.
http://php.net/supported-versions.php

Some auditors make their decision based on the level of support the installed PHP Version has.  7.0 will go from supported to Security Fixes Only in January 2018, and no support January 2019

This leaves 1.x sites which are not end of life from January 2018 till November 2017 with potential business[though not technical] issues.

Jumping directly to 7.1 avoids business issues at the cost of a few technical issues.

**Comment by icurdinj** [comment]
@gamort : "I think a better solution would be to disable those warnings[since no one reads them anyway]"
@benjamw : "I have my error reporting turned all the way up (E_ALL), so I'm not hiding anything when I code. "

Round 1, fight! :-)

**Comment by benjamw** [comment]
*POW* *BIFF* *BANG*

TABS ARE BETTER THAN SPACES!

**Comment by icurdinj** [comment]
I agree that tabs are better than spaces!
But, PSR-2...
And standards are better than chaos...
Damn...
